name: bookmark_api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:

  bookmark_models:
    git:
      ref: master
      url: git@github.com:VHCBlade/bookmark_models.git

  dart_frog: ^0.3.0
  dart_frog_cors: ^1.0.0

  event_bloc: ^4.2.1
  event_db: ^0.1.3
  event_hive: ^0.1.5+1

  hive: ^2.2.3
  intl: ^0.18.0
  tuple: ^2.0.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
